[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}" 
mumbai = "${POLYGON_MUMBAI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config